version: '3'

services:
    db:
        image: mariadb:10.3
        environment:
            MYSQL_ROOT_PASSWORD: rootGreatPassword
            MYSQL_DATABASE: app
            MYSQL_USER: userapp
            MYSQL_PASSWORD: passworduserapp
        restart: always
        volumes:
            - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

    api:
        build: api
        container_name: app_backend
        restart: always
        environment:
            DB_HOST: db
            DB_PORT: 3306
            DB_USERNAME: userapp
            DB_PASSWORD: passworduserapp
            DB_NAME: app
            
        ports:
            - "4000:4000"
    
    frontend:
        build: client
        container_name: app_frontend
        restart: always
        environment:
            PORT: 4001
            API_URL: "http://localhost:4000/v1"
        ports:
            - "4001:4001"
